#!/bin/bash

# sysinfo_page - A script to produce an HTML file

# Constants

title="My System Information"
RIGHT_NOW=$(date +"%x %r %Z")
TIME_STAMP="Updated on $RIGHT_NOW by $USER"

# Functions

system_info()
{

}

show_uptime()
{

}

drive_space()
{

}

home_space()
{

}

# Main

cat <<- _EOF_
    <html>
     <head>
        <title>
            $title $HOSTNAME
        </title>
    </head>
                
    <body>
        <h1>
            $title $HOSTNAME
        </h1>
            <p>$TIME_STAMP<p>
            $(system_info)
            $(show_uptime)
            $(drive_space)
            $(home_space)
    </body>
    </html>
_EOF_
